import { Supplier, WebSignal, SupplierNetwork, IntelligenceBrief, RiskScore } from './types';

// ─── Demo Suppliers ─────────────────────────────────────────────────────────

const demoRiskScores: Record<string, RiskScore> = {
  'sakura-silicon': {
    overall: 32,
    level: 'low',
    categories: [
      { category: 'financial', score: 20, label: 'Financial Health', signals: 3, trend: 'stable' },
      { category: 'operational', score: 15, label: 'Operational Stability', signals: 2, trend: 'stable' },
      { category: 'leadership', score: 10, label: 'Leadership Changes', signals: 1, trend: 'stable' },
      { category: 'hiring', score: 25, label: 'Hiring Momentum', signals: 2, trend: 'down' },
      { category: 'regulatory', score: 18, label: 'Regulatory & Compliance', signals: 1, trend: 'stable' },
      { category: 'reputation', score: 12, label: 'Reputation & Sentiment', signals: 2, trend: 'stable' },
      { category: 'product_pricing', score: 22, label: 'Product & Pricing', signals: 1, trend: 'stable' },
      { category: 'cyber', score: 5, label: 'Cyber Exposure', signals: 0, trend: 'stable' },
    ],
    explanation: 'Overall risk is low. Strong financial health and stable operations observed.',
    lastCalculated: new Date().toISOString(),
  },
  'han-river': {
    overall: 74,
    level: 'high',
    categories: [
      { category: 'financial', score: 65, label: 'Financial Health', signals: 4, trend: 'up' },
      { category: 'operational', score: 70, label: 'Operational Stability', signals: 3, trend: 'up' },
      { category: 'leadership', score: 82, label: 'Leadership Changes', signals: 3, trend: 'up' },
      { category: 'hiring', score: 55, label: 'Hiring Momentum', signals: 2, trend: 'up' },
      { category: 'regulatory', score: 40, label: 'Regulatory & Compliance', signals: 2, trend: 'stable' },
      { category: 'reputation', score: 60, label: 'Reputation & Sentiment', signals: 3, trend: 'up' },
      { category: 'product_pricing', score: 45, label: 'Product & Pricing', signals: 2, trend: 'up' },
      { category: 'cyber', score: 30, label: 'Cyber Exposure', signals: 1, trend: 'stable' },
    ],
    explanation: 'Elevated risk detected in leadership changes and operational stability. CEO departure and production delays raise concern.',
    lastCalculated: new Date().toISOString(),
  },
  'nordic-litho': {
    overall: 28,
    level: 'low',
    categories: [
      { category: 'financial', score: 15, label: 'Financial Health', signals: 2, trend: 'down' },
      { category: 'operational', score: 20, label: 'Operational Stability', signals: 2, trend: 'stable' },
      { category: 'leadership', score: 10, label: 'Leadership Changes', signals: 1, trend: 'stable' },
      { category: 'hiring', score: 8, label: 'Hiring Momentum', signals: 3, trend: 'down' },
      { category: 'regulatory', score: 12, label: 'Regulatory & Compliance', signals: 1, trend: 'stable' },
      { category: 'reputation', score: 10, label: 'Reputation & Sentiment', signals: 2, trend: 'stable' },
      { category: 'product_pricing', score: 18, label: 'Product & Pricing', signals: 1, trend: 'stable' },
      { category: 'cyber', score: 5, label: 'Cyber Exposure', signals: 0, trend: 'stable' },
    ],
    explanation: 'Overall risk is low. Strong hiring expansion signals indicate growth phase.',
    lastCalculated: new Date().toISOString(),
  },
  'straits-substrate': {
    overall: 52,
    level: 'medium',
    categories: [
      { category: 'financial', score: 45, label: 'Financial Health', signals: 3, trend: 'up' },
      { category: 'operational', score: 55, label: 'Operational Stability', signals: 2, trend: 'up' },
      { category: 'leadership', score: 30, label: 'Leadership Changes', signals: 1, trend: 'stable' },
      { category: 'hiring', score: 40, label: 'Hiring Momentum', signals: 2, trend: 'stable' },
      { category: 'regulatory', score: 60, label: 'Regulatory & Compliance', signals: 3, trend: 'up' },
      { category: 'reputation', score: 45, label: 'Reputation & Sentiment', signals: 2, trend: 'up' },
      { category: 'product_pricing', score: 50, label: 'Product & Pricing', signals: 2, trend: 'up' },
      { category: 'cyber', score: 20, label: 'Cyber Exposure', signals: 1, trend: 'stable' },
    ],
    explanation: 'Medium risk due to regulatory scrutiny and pricing instability. Export compliance review underway.',
    lastCalculated: new Date().toISOString(),
  },
  'pacific-rare': {
    overall: 78,
    level: 'high',
    categories: [
      { category: 'financial', score: 72, label: 'Financial Health', signals: 4, trend: 'up' },
      { category: 'operational', score: 80, label: 'Operational Stability', signals: 3, trend: 'up' },
      { category: 'leadership', score: 45, label: 'Leadership Changes', signals: 2, trend: 'stable' },
      { category: 'hiring', score: 60, label: 'Hiring Momentum', signals: 2, trend: 'up' },
      { category: 'regulatory', score: 85, label: 'Regulatory & Compliance', signals: 4, trend: 'up' },
      { category: 'reputation', score: 70, label: 'Reputation & Sentiment', signals: 3, trend: 'up' },
      { category: 'product_pricing', score: 75, label: 'Product & Pricing', signals: 3, trend: 'up' },
      { category: 'cyber', score: 15, label: 'Cyber Exposure', signals: 0, trend: 'stable' },
    ],
    explanation: 'High risk due to regulatory sanctions and supply disruption. Export controls impacting raw material availability.',
    lastCalculated: new Date().toISOString(),
  },
  'rhine-eda': {
    overall: 22,
    level: 'low',
    categories: [
      { category: 'financial', score: 10, label: 'Financial Health', signals: 2, trend: 'down' },
      { category: 'operational', score: 15, label: 'Operational Stability', signals: 1, trend: 'stable' },
      { category: 'leadership', score: 8, label: 'Leadership Changes', signals: 1, trend: 'stable' },
      { category: 'hiring', score: 5, label: 'Hiring Momentum', signals: 2, trend: 'down' },
      { category: 'regulatory', score: 20, label: 'Regulatory & Compliance', signals: 1, trend: 'stable' },
      { category: 'reputation', score: 8, label: 'Reputation & Sentiment', signals: 2, trend: 'down' },
      { category: 'product_pricing', score: 15, label: 'Product & Pricing', signals: 1, trend: 'stable' },
      { category: 'cyber', score: 10, label: 'Cyber Exposure', signals: 1, trend: 'stable' },
    ],
    explanation: 'Overall risk is low. Strong market position and positive customer sentiment.',
    lastCalculated: new Date().toISOString(),
  },
  'andes-logistics': {
    overall: 61,
    level: 'medium',
    categories: [
      { category: 'financial', score: 50, label: 'Financial Health', signals: 3, trend: 'up' },
      { category: 'operational', score: 72, label: 'Operational Stability', signals: 4, trend: 'up' },
      { category: 'leadership', score: 35, label: 'Leadership Changes', signals: 1, trend: 'stable' },
      { category: 'hiring', score: 45, label: 'Hiring Momentum', signals: 2, trend: 'stable' },
      { category: 'regulatory', score: 55, label: 'Regulatory & Compliance', signals: 2, trend: 'up' },
      { category: 'reputation', score: 65, label: 'Reputation & Sentiment', signals: 3, trend: 'up' },
      { category: 'product_pricing', score: 60, label: 'Product & Pricing', signals: 2, trend: 'up' },
      { category: 'cyber', score: 25, label: 'Cyber Exposure', signals: 1, trend: 'stable' },
    ],
    explanation: 'Medium risk due to logistics disruptions and rising operational costs impacting delivery reliability.',
    lastCalculated: new Date().toISOString(),
  },
  'meridian-battery': {
    overall: 71,
    level: 'high',
    categories: [
      { category: 'financial', score: 60, label: 'Financial Health', signals: 3, trend: 'up' },
      { category: 'operational', score: 65, label: 'Operational Stability', signals: 3, trend: 'up' },
      { category: 'leadership', score: 50, label: 'Leadership Changes', signals: 2, trend: 'up' },
      { category: 'hiring', score: 75, label: 'Hiring Momentum', signals: 3, trend: 'up' },
      { category: 'regulatory', score: 80, label: 'Regulatory & Compliance', signals: 4, trend: 'up' },
      { category: 'reputation', score: 55, label: 'Reputation & Sentiment', signals: 2, trend: 'stable' },
      { category: 'product_pricing', score: 70, label: 'Product & Pricing', signals: 3, trend: 'up' },
      { category: 'cyber', score: 20, label: 'Cyber Exposure', signals: 1, trend: 'stable' },
    ],
    explanation: 'High risk due to environmental compliance investigation and raw material cost volatility.',
    lastCalculated: new Date().toISOString(),
  },
};

export const demoSuppliers: Supplier[] = [
  {
    id: 'sakura-silicon',
    name: 'Sakura Silicon Works',
    country: 'Japan',
    industry: 'Semiconductor Manufacturing',
    website: 'https://sakurasilicon.example.com',
    relationshipType: 'Wafer Foundry',
    importance: 'critical',
    riskScore: demoRiskScores['sakura-silicon'],
    lastUpdated: new Date(Date.now() - 2 * 3600000).toISOString(),
    description: 'Leading 300mm wafer fabrication facility specializing in advanced node process technology for EV power semiconductors.',
    signalCount: 5,
  },
  {
    id: 'han-river',
    name: 'Han River Advanced Packaging',
    country: 'South Korea',
    industry: 'OSAT Services',
    website: 'https://hanriverap.example.com',
    relationshipType: 'OSAT Provider',
    importance: 'high',
    riskScore: demoRiskScores['han-river'],
    lastUpdated: new Date(Date.now() - 1 * 3600000).toISOString(),
    description: 'Advanced semiconductor packaging and testing services. Key provider of flip-chip and fan-out wafer-level packaging.',
    signalCount: 7,
  },
  {
    id: 'nordic-litho',
    name: 'Nordic Lithography Systems',
    country: 'Sweden',
    industry: 'Semiconductor Equipment',
    website: 'https://nordicls.example.com',
    relationshipType: 'Equipment Supplier',
    importance: 'high',
    riskScore: demoRiskScores['nordic-litho'],
    lastUpdated: new Date(Date.now() - 5 * 3600000).toISOString(),
    description: 'Precision lithography and metrology equipment for advanced semiconductor manufacturing processes.',
    signalCount: 4,
  },
  {
    id: 'straits-substrate',
    name: 'Straits Substrate Technologies',
    country: 'Singapore',
    industry: 'Electronic Materials',
    website: 'https://straitssub.example.com',
    relationshipType: 'Substrate Supplier',
    importance: 'medium',
    riskScore: demoRiskScores['straits-substrate'],
    lastUpdated: new Date(Date.now() - 3 * 3600000).toISOString(),
    description: 'High-performance IC substrates and advanced PCB materials for automotive and industrial applications.',
    signalCount: 5,
  },
  {
    id: 'pacific-rare',
    name: 'Pacific Rare Materials',
    country: 'Australia',
    industry: 'Mining & Materials',
    website: 'https://pacificrare.example.com',
    relationshipType: 'Battery Materials Supplier',
    importance: 'critical',
    riskScore: demoRiskScores['pacific-rare'],
    lastUpdated: new Date(Date.now() - 0.5 * 3600000).toISOString(),
    description: 'Lithium and rare earth mineral extraction and processing for EV battery cathode materials.',
    signalCount: 8,
  },
  {
    id: 'rhine-eda',
    name: 'Rhine EDA Systems',
    country: 'Germany',
    industry: 'EDA Software',
    website: 'https://rhineeda.example.com',
    relationshipType: 'EDA Software Vendor',
    importance: 'medium',
    riskScore: demoRiskScores['rhine-eda'],
    lastUpdated: new Date(Date.now() - 8 * 3600000).toISOString(),
    description: 'Electronic design automation tools for chip architecture, simulation, and verification workflows.',
    signalCount: 3,
  },
  {
    id: 'andes-logistics',
    name: 'Andes Logistics Group',
    country: 'Chile',
    industry: 'Supply Chain Logistics',
    website: 'https://andeslog.example.com',
    relationshipType: 'Logistics Provider',
    importance: 'medium',
    riskScore: demoRiskScores['andes-logistics'],
    lastUpdated: new Date(Date.now() - 4 * 3600000).toISOString(),
    description: 'Specialized hazardous and temperature-controlled logistics for battery materials and semiconductor components.',
    signalCount: 6,
  },
  {
    id: 'meridian-battery',
    name: 'Meridian Battery Chemicals',
    country: 'Canada',
    industry: 'Specialty Chemicals',
    website: 'https://meridianbattery.example.com',
    relationshipType: 'Specialty Chemicals Supplier',
    importance: 'high',
    riskScore: demoRiskScores['meridian-battery'],
    lastUpdated: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    description: 'Electrolyte formulations and cathode active materials for next-generation lithium-ion battery cells.',
    signalCount: 7,
  },
];

// ─── Demo Web Signals ───────────────────────────────────────────────────────

export const demoSignals: WebSignal[] = [
  // Sakura Silicon (low risk - 5 signals)
  { id: 'sig-001', supplierId: 'sakura-silicon', sourceType: 'news', title: 'Sakura Silicon Reports Record Q3 Revenue', summary: 'Quarterly revenue up 12% YoY driven by EV semiconductor demand.', url: 'https://techcrunch.example.com/sakura-q3', publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'financial', confidence: 0.92 },
  { id: 'sig-002', supplierId: 'sakura-silicon', sourceType: 'press_release', title: 'New 5nm Process Line Announced', summary: 'Sakura Silicon invests $2B in next-gen fabrication capacity.', url: 'https://sakurasilicon.example.com/press/5nm', publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'operational', confidence: 0.95 },
  { id: 'sig-003', supplierId: 'sakura-silicon', sourceType: 'news', title: 'Japan Semiconductor Policy Boosts Domestic Foundries', summary: 'Government subsidies support capacity expansion for domestic chipmakers.', url: 'https://reuters.example.com/japan-semicon', publishedAt: new Date(Date.now() - 8 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'regulatory', confidence: 0.88 },
  { id: 'sig-004', supplierId: 'sakura-silicon', sourceType: 'job_posting', title: 'Sakura Silicon Hiring 200+ Engineers', summary: 'Major hiring push for advanced node process engineers and equipment specialists.', url: 'https://linkedin.example.com/sakura-jobs', publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'hiring', confidence: 0.85 },
  { id: 'sig-005', supplierId: 'sakura-silicon', sourceType: 'industry_report', title: 'Minor Yield Issue at Sakura Fab 3', summary: 'Industry sources report temporary yield dip at new production line.', url: 'https://semianalysis.example.com/sakura-yield', publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'operational', confidence: 0.65 },

  // Han River (high risk - 7 signals)
  { id: 'sig-006', supplierId: 'han-river', sourceType: 'news', title: 'Han River CEO Announces Sudden Departure', summary: 'CEO Park Min-jun steps down citing personal reasons. Board names interim leadership.', url: 'https://bloomberg.example.com/hanriver-ceo', publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'leadership', confidence: 0.96 },
  { id: 'sig-007', supplierId: 'han-river', sourceType: 'news', title: 'Production Delays at Han River Packaging Facility', summary: 'Equipment failures cause 3-week delay in advanced packaging orders.', url: 'https://reuters.example.com/hanriver-delay', publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'operational', confidence: 0.91 },
  { id: 'sig-008', supplierId: 'han-river', sourceType: 'financial_report', title: 'Han River Q2 Earnings Miss Estimates', summary: 'Revenue fell 8% below analyst consensus. Margins compressed due to material costs.', url: 'https://ft.example.com/hanriver-earnings', publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'financial', confidence: 0.93 },
  { id: 'sig-009', supplierId: 'han-river', sourceType: 'news', title: 'Two Senior VPs Leave Han River This Month', summary: 'VP of Operations and VP of R&D both resign within two weeks.', url: 'https://techcrunch.example.com/hanriver-exits', publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'leadership', confidence: 0.89 },
  { id: 'sig-010', supplierId: 'han-river', sourceType: 'social_media', title: 'Employee Reviews Flag Quality Concerns', summary: 'Glassdoor reviews mention declining quality standards and rushed timelines.', url: 'https://glassdoor.example.com/hanriver', publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'reputation', confidence: 0.72 },
  { id: 'sig-011', supplierId: 'han-river', sourceType: 'news', title: 'Han River Faces Supply Chain Bottleneck', summary: 'Key substrate supplier delays impacting packaging throughput.', url: 'https://semiengineering.example.com/hanriver', publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'product_pricing', confidence: 0.84 },
  { id: 'sig-012', supplierId: 'han-river', sourceType: 'press_release', title: 'Han River Secures New Automotive Client', summary: 'Despite challenges, Han River signs multi-year deal with European automaker.', url: 'https://hanriverap.example.com/press/auto', publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'financial', confidence: 0.88 },

  // Nordic Litho (low risk - 4 signals)
  { id: 'sig-013', supplierId: 'nordic-litho', sourceType: 'news', title: 'Nordic Lithography Wins Industry Innovation Award', summary: 'Recognized for breakthrough in EUV metrology at SEMICON Europe.', url: 'https://eenews.example.com/nordic-award', publishedAt: new Date(Date.now() - 6 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'reputation', confidence: 0.90 },
  { id: 'sig-014', supplierId: 'nordic-litho', sourceType: 'job_posting', title: 'Nordic Litho Expanding R&D Team by 30%', summary: 'Aggressive hiring across optical engineering and AI-driven inspection roles.', url: 'https://linkedin.example.com/nordic-hiring', publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'hiring', confidence: 0.87 },
  { id: 'sig-015', supplierId: 'nordic-litho', sourceType: 'financial_report', title: 'Nordic Litho Full Year Revenue Up 18%', summary: 'Strong demand for advanced metrology tools drives record annual performance.', url: 'https://ft.example.com/nordic-fy', publishedAt: new Date(Date.now() - 12 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'financial', confidence: 0.94 },
  { id: 'sig-016', supplierId: 'nordic-litho', sourceType: 'press_release', title: 'Partnership with Major Asian Foundry', summary: 'Nordic Litho secures long-term tool supply agreement with top-3 foundry.', url: 'https://nordicls.example.com/press/partnership', publishedAt: new Date(Date.now() - 9 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'operational', confidence: 0.91 },

  // Straits Substrate (medium risk - 5 signals)
  { id: 'sig-017', supplierId: 'straits-substrate', sourceType: 'government', title: 'Singapore Tightens Chemical Export Controls', summary: 'New export licensing requirements for specialty substrate materials.', url: 'https://gov.sg.example.com/export-controls', publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'regulatory', confidence: 0.93 },
  { id: 'sig-018', supplierId: 'straits-substrate', sourceType: 'news', title: 'Straits Substrate Material Costs Rising', summary: 'Raw material price increases of 15-20% expected to impact margins.', url: 'https://cnbc.example.com/straits-costs', publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'product_pricing', confidence: 0.86 },
  { id: 'sig-019', supplierId: 'straits-substrate', sourceType: 'news', title: 'Straits Wins Best Supplier Award from OEM', summary: 'Named top substrate supplier by a leading automotive chip manufacturer.', url: 'https://eenews.example.com/straits-award', publishedAt: new Date(Date.now() - 14 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'reputation', confidence: 0.85 },
  { id: 'sig-020', supplierId: 'straits-substrate', sourceType: 'news', title: 'Straits Substrate Under Review for Trade Compliance', summary: 'Regulatory body reviews export documentation practices.', url: 'https://reuters.example.com/straits-review', publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'regulatory', confidence: 0.79 },
  { id: 'sig-021', supplierId: 'straits-substrate', sourceType: 'financial_report', title: 'Straits Q1 Revenue Flat Year-over-Year', summary: 'Stable revenue but declining margins raise analyst concern.', url: 'https://ft.example.com/straits-q1', publishedAt: new Date(Date.now() - 8 * 86400000).toISOString(), sentiment: 'neutral', riskCategory: 'financial', confidence: 0.90 },

  // Pacific Rare (high risk - 8 signals)
  { id: 'sig-022', supplierId: 'pacific-rare', sourceType: 'government', title: 'Critical Minerals Export Ban Impacts Pacific Rare', summary: 'New government regulations restrict lithium exports from key mining region.', url: 'https://gov.au.example.com/minerals-ban', publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'regulatory', confidence: 0.97 },
  { id: 'sig-023', supplierId: 'pacific-rare', sourceType: 'news', title: 'Pacific Rare Faces Environmental Compliance Investigation', summary: 'Federal environmental agency launches probe into tailings management practices.', url: 'https://reuters.example.com/pacific-enviro', publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'regulatory', confidence: 0.94 },
  { id: 'sig-024', supplierId: 'pacific-rare', sourceType: 'news', title: 'Lithium Spot Prices Surge 25% on Supply Fears', summary: 'Market volatility drives battery material costs to 18-month high.', url: 'https://bloomberg.example.com/lithium-surge', publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'product_pricing', confidence: 0.92 },
  { id: 'sig-025', supplierId: 'pacific-rare', sourceType: 'news', title: 'Pacific Rare Mine Shutdown for Safety Review', summary: 'Primary extraction site temporarily halted pending safety audit.', url: 'https://mining.example.com/pacific-shutdown', publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'operational', confidence: 0.91 },
  { id: 'sig-026', supplierId: 'pacific-rare', sourceType: 'financial_report', title: 'Pacific Rare Credit Rating Under Review', summary: 'Major credit agency places rating on negative watchlist.', url: 'https://ft.example.com/pacific-credit', publishedAt: new Date(Date.now() - 6 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'financial', confidence: 0.93 },
  { id: 'sig-027', supplierId: 'pacific-rare', sourceType: 'news', title: 'Pacific Rare Announces Workforce Reduction', summary: '15% workforce reduction planned as part of cost restructuring.', url: 'https://cnbc.example.com/pacific-layoffs', publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'hiring', confidence: 0.90 },
  { id: 'sig-028', supplierId: 'pacific-rare', sourceType: 'social_media', title: 'Community Protest Against Pacific Rare Mining Operations', summary: 'Local communities organize protests over water contamination concerns.', url: 'https://reddit.example.com/pacific-protest', publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'reputation', confidence: 0.75 },
  { id: 'sig-029', supplierId: 'pacific-rare', sourceType: 'press_release', title: 'Pacific Rare Invests in Sustainable Extraction R&D', summary: 'New research partnership aims to reduce environmental footprint of mining.', url: 'https://pacificrare.example.com/press/green', publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'reputation', confidence: 0.82 },

  // Rhine EDA (low risk - 3 signals)
  { id: 'sig-030', supplierId: 'rhine-eda', sourceType: 'press_release', title: 'Rhine EDA Launches AI-Powered Design Suite', summary: 'Next-generation EDA platform integrates machine learning for design optimization.', url: 'https://rhineeda.example.com/press/ai-suite', publishedAt: new Date(Date.now() - 7 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'product_pricing', confidence: 0.91 },
  { id: 'sig-031', supplierId: 'rhine-eda', sourceType: 'news', title: 'Rhine EDA Customer Satisfaction Hits Record High', summary: 'Annual customer survey shows 94% satisfaction rate.', url: 'https://eenews.example.com/rhine-satisfaction', publishedAt: new Date(Date.now() - 15 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'reputation', confidence: 0.87 },
  { id: 'sig-032', supplierId: 'rhine-eda', sourceType: 'financial_report', title: 'Rhine EDA Raises Full-Year Revenue Guidance', summary: 'Company raises FY guidance citing strong chip design demand.', url: 'https://ft.example.com/rhine-guidance', publishedAt: new Date(Date.now() - 11 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'financial', confidence: 0.93 },

  // Andes Logistics (medium risk - 6 signals)
  { id: 'sig-033', supplierId: 'andes-logistics', sourceType: 'news', title: 'Port Congestion Disrupts Andes Logistics Routes', summary: 'Key South American shipping routes experiencing 2-3 week delays.', url: 'https://reuters.example.com/andes-port', publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'operational', confidence: 0.89 },
  { id: 'sig-034', supplierId: 'andes-logistics', sourceType: 'news', title: 'Fuel Cost Surge Impacts Logistics Margins', summary: 'Regional fuel price increases of 22% drive up transportation costs.', url: 'https://cnbc.example.com/andes-fuel', publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'financial', confidence: 0.86 },
  { id: 'sig-035', supplierId: 'andes-logistics', sourceType: 'news', title: 'Andes Logistics Fined for Customs Documentation Errors', summary: 'Regulatory fine issued for repeated customs filing inaccuracies.', url: 'https://reuters.example.com/andes-fine', publishedAt: new Date(Date.now() - 6 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'regulatory', confidence: 0.91 },
  { id: 'sig-036', supplierId: 'andes-logistics', sourceType: 'review', title: 'Client Reviews Flag Declining On-Time Performance', summary: 'On-time delivery rate dropped from 94% to 87% over past quarter.', url: 'https://supplychainreview.example.com/andes', publishedAt: new Date(Date.now() - 8 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'reputation', confidence: 0.80 },
  { id: 'sig-037', supplierId: 'andes-logistics', sourceType: 'press_release', title: 'Andes Logistics Opens New Cold-Chain Facility', summary: 'New temperature-controlled warehouse in Santiago for battery materials.', url: 'https://andeslog.example.com/press/cold-chain', publishedAt: new Date(Date.now() - 12 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'operational', confidence: 0.88 },
  { id: 'sig-038', supplierId: 'andes-logistics', sourceType: 'news', title: 'Andes Logistics Exploring EV Fleet Conversion', summary: 'Pilot program to convert 30% of fleet to electric vehicles by 2026.', url: 'https://greenlogistics.example.com/andes-ev', publishedAt: new Date(Date.now() - 9 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'reputation', confidence: 0.83 },

  // Meridian Battery (high risk - 7 signals)
  { id: 'sig-039', supplierId: 'meridian-battery', sourceType: 'government', title: 'Environmental Agency Launches Probe into Meridian Battery', summary: 'Federal investigation into chemical waste disposal practices at main facility.', url: 'https://gov.ca.example.com/meridian-probe', publishedAt: new Date(Date.now() - 1 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'regulatory', confidence: 0.95 },
  { id: 'sig-040', supplierId: 'meridian-battery', sourceType: 'news', title: 'Meridian Battery Electrolyte Prices Jump 18%', summary: 'Key electrolyte formulation costs rise due to precursor material shortage.', url: 'https://bloomberg.example.com/meridian-prices', publishedAt: new Date(Date.now() - 3 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'product_pricing', confidence: 0.90 },
  { id: 'sig-041', supplierId: 'meridian-battery', sourceType: 'news', title: 'Meridian Battery CFO Resigns Unexpectedly', summary: 'CFO departure raises questions about financial reporting timeline.', url: 'https://ft.example.com/meridian-cfo', publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'leadership', confidence: 0.92 },
  { id: 'sig-042', supplierId: 'meridian-battery', sourceType: 'job_posting', title: 'Meridian Battery Hiring Surge: 500 Positions', summary: 'Massive recruitment drive for new production facility. Quality control roles tripled.', url: 'https://indeed.example.com/meridian-jobs', publishedAt: new Date(Date.now() - 4 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'hiring', confidence: 0.86 },
  { id: 'sig-043', supplierId: 'meridian-battery', sourceType: 'financial_report', title: 'Meridian Battery Debt-to-Equity Ratio Spikes', summary: 'Latest filing shows significant increase in leverage for facility expansion.', url: 'https://ft.example.com/meridian-debt', publishedAt: new Date(Date.now() - 8 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'financial', confidence: 0.91 },
  { id: 'sig-044', supplierId: 'meridian-battery', sourceType: 'news', title: 'Competitor Launches Alternative Electrolyte Formula', summary: 'New market entrant threatens Meridian battery differentiation.', url: 'https://techcrunch.example.com/electrolyte-alt', publishedAt: new Date(Date.now() - 6 * 86400000).toISOString(), sentiment: 'negative', riskCategory: 'product_pricing', confidence: 0.78 },
  { id: 'sig-045', supplierId: 'meridian-battery', sourceType: 'press_release', title: 'Meridian Battery Signs Strategic Partnership with EV OEM', summary: 'Multi-year supply agreement with major electric vehicle manufacturer.', url: 'https://meridianbattery.example.com/press/oem', publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(), sentiment: 'positive', riskCategory: 'financial', confidence: 0.89 },
];

// ─── Demo Network ───────────────────────────────────────────────────────────

export const demoNetwork: SupplierNetwork = {
  centerNode: {
    id: 'center',
    name: 'EV Battery Supply Chain',
    type: 'industry',
  },
  suppliers: demoSuppliers.map(s => ({
    id: s.id,
    name: s.name,
    country: s.country,
    riskLevel: s.riskScore.level,
    riskScore: s.riskScore.overall,
    importance: s.importance,
    signalCount: s.signalCount,
  })),
  edges: demoSuppliers.map(s => ({
    source: 'center',
    target: s.id,
    relationship: s.relationshipType,
  })),
};

// ─── Demo Brief ─────────────────────────────────────────────────────────────

export const demoBrief: IntelligenceBrief = {
  id: 'brief-demo-001',
  generatedAt: new Date().toISOString(),
  query: 'EV Battery Supply Chain Risk Scan',
  executiveSummary: 'Analysis of 8 suppliers across the EV battery supply chain reveals 3 high-risk entities requiring immediate attention. Pacific Rare Materials faces regulatory sanctions and supply disruption from export controls. Han River Advanced Packaging is experiencing leadership instability with CEO departure and key executive exits. Meridian Battery Chemicals is under environmental compliance investigation with rising input costs. Two suppliers show medium risk from logistics disruptions and regulatory reviews. Three suppliers maintain low risk profiles with strong financial performance and positive growth signals.',
  topRisks: [
    { title: 'Critical Mineral Export Restrictions', description: 'Government export ban directly impacts lithium supply from Pacific Rare Materials, threatening battery material availability for 60+ days.', severity: 'high', supplier: 'Pacific Rare Materials' },
    { title: 'Leadership Instability at Key OSAT Provider', description: 'CEO departure and two senior VP exits at Han River Advanced Packaging within 2 weeks. Production delays already reported.', severity: 'high', supplier: 'Han River Advanced Packaging' },
    { title: 'Environmental Compliance Investigation', description: 'Federal probe into Meridian Battery Chemicals waste disposal practices could result in operational restrictions or fines.', severity: 'high', supplier: 'Meridian Battery Chemicals' },
  ],
  topOpportunities: [
    { title: 'Nordic Lithography Expansion', description: 'Nordic Lithography Systems expanding R&D team by 30% and winning industry awards—strong partner for next-gen equipment needs.', supplier: 'Nordic Lithography Systems' },
    { title: 'Meridian Battery Hiring Surge', description: 'Despite risks, Meridian Battery is hiring 500 positions for new production facility, signaling capacity growth.', supplier: 'Meridian Battery Chemicals' },
    { title: 'Sakura Silicon Capacity Investment', description: 'Sakura Silicon investing $2B in 5nm process line—potential to secure advanced node allocation.', supplier: 'Sakura Silicon Works' },
  ],
  recommendedActions: [
    'Initiate contingency sourcing for lithium and rare earth materials to reduce Pacific Rare dependency',
    'Schedule executive review with Han River interim leadership to assess operational continuity',
    'Request environmental compliance update from Meridian Battery and assess backup electrolyte suppliers',
    'Accelerate qualification of Straits Substrate alternative sources given regulatory review',
    'Lock in long-term pricing with Nordic Lithography before demand-driven cost increases',
    'Review Andes Logistics SLAs given declining on-time delivery performance',
  ],
  monitoringFrequency: 'Daily monitoring recommended for high-risk suppliers. Weekly for medium-risk. Bi-weekly for low-risk.',
  confidenceLevel: 0.82,
  supplierCount: 8,
  signalCount: 45,
};
