'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { Nav } from '@/components/nav';
import { RiskBadge } from '@/components/risk-badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { IntelligenceBrief } from '@/lib/types';
import { demoBrief } from '@/lib/demo-data';
import {
  FileText, AlertTriangle, TrendingUp, CheckCircle2, Clock,
  Copy, Printer, Shield, Radar,
} from 'lucide-react';

function BriefContent() {
  const searchParams = useSearchParams();
  const query = searchParams.get('q') || 'EV Battery Supply Chain Risk Scan';
  const [brief, setBrief] = useState<IntelligenceBrief | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/brief', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query }),
    })
      .then(r => r.json())
      .then(data => setBrief(data))
      .catch(() => setBrief(demoBrief))
      .finally(() => setLoading(false));
  }, [query]);

  function handleCopy() {
    if (!brief) return;
    const text = `KEIRETSU RADAR — EXECUTIVE RISK BRIEF
${'='.repeat(50)}
Query: ${brief.query}
Generated: ${new Date(brief.generatedAt).toLocaleString()}
Suppliers Analyzed: ${brief.supplierCount}
Signals Processed: ${brief.signalCount}
Confidence: ${Math.round(brief.confidenceLevel * 100)}%

EXECUTIVE SUMMARY
${brief.executiveSummary}

TOP RISKS
${brief.topRisks.map((r, i) => `${i + 1}. [${r.severity.toUpperCase()}] ${r.title} (${r.supplier})\n   ${r.description}`).join('\n')}

OPPORTUNITIES
${brief.topOpportunities.map((o, i) => `${i + 1}. ${o.title} (${o.supplier})\n   ${o.description}`).join('\n')}

RECOMMENDED ACTIONS
${brief.recommendedActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

MONITORING: ${brief.monitoringFrequency}

Generated by Keiretsu Radar — Powered by Bright Data & AI`;

    navigator.clipboard.writeText(text);
  }

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col">
        <Nav />
        <div className="flex-1 flex items-center justify-center">
          <div className="flex flex-col items-center gap-3">
            <div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full" />
            <p className="text-sm text-muted-foreground">Generating executive brief...</p>
          </div>
        </div>
      </div>
    );
  }

  if (!brief) return null;

  return (
    <div className="min-h-screen flex flex-col">
      <Nav />

      <main className="flex-1">
        <div className="mx-auto max-w-4xl px-4 py-6 space-y-6">
          {/* Header */}
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10">
                  <FileText className="h-4 w-4 text-primary" />
                </div>
                <h1 className="text-xl font-bold">Boardroom Risk Brief</h1>
              </div>
              <p className="text-sm text-muted-foreground">{brief.query}</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="gap-1.5" onClick={handleCopy}>
                <Copy className="h-3.5 w-3.5" /> Copy
              </Button>
              <Button variant="outline" size="sm" className="gap-1.5" onClick={() => window.print()}>
                <Printer className="h-3.5 w-3.5" /> Print
              </Button>
            </div>
          </div>

          {/* Meta */}
          <div className="flex flex-wrap gap-3">
            <Badge variant="outline" className="gap-1.5 text-xs">
              <Clock className="h-3 w-3" />
              {new Date(brief.generatedAt).toLocaleDateString()}
            </Badge>
            <Badge variant="outline" className="gap-1.5 text-xs">
              <Shield className="h-3 w-3" />
              {brief.supplierCount} Suppliers
            </Badge>
            <Badge variant="outline" className="gap-1.5 text-xs">
              <Radar className="h-3 w-3" />
              {brief.signalCount} Signals
            </Badge>
            <Badge variant="outline" className="gap-1.5 text-xs">
              Confidence: {Math.round(brief.confidenceLevel * 100)}%
            </Badge>
          </div>

          {/* Executive Summary */}
          <Card className="bg-card/50 border-border/50">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Executive Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm leading-relaxed text-muted-foreground">{brief.executiveSummary}</p>
            </CardContent>
          </Card>

          {/* Top Risks */}
          <div>
            <h2 className="text-sm font-medium text-muted-foreground mb-3 flex items-center gap-2">
              <AlertTriangle className="h-4 w-4 text-red-400" /> Top Risks
            </h2>
            <div className="space-y-3">
              {brief.topRisks.map((risk, i) => (
                <Card key={i} className="bg-card/50 border-border/50 border-l-2 border-l-red-500/40">
                  <CardContent className="pt-4 pb-3">
                    <div className="flex items-start justify-between gap-2 mb-1">
                      <h3 className="font-medium text-sm">{risk.title}</h3>
                      <RiskBadge level={risk.severity} />
                    </div>
                    <p className="text-xs text-muted-foreground mb-2">{risk.description}</p>
                    <Badge variant="outline" className="text-[10px]">{risk.supplier}</Badge>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* Opportunities */}
          <div>
            <h2 className="text-sm font-medium text-muted-foreground mb-3 flex items-center gap-2">
              <TrendingUp className="h-4 w-4 text-emerald-400" /> Opportunities
            </h2>
            <div className="space-y-3">
              {brief.topOpportunities.map((opp, i) => (
                <Card key={i} className="bg-card/50 border-border/50 border-l-2 border-l-emerald-500/40">
                  <CardContent className="pt-4 pb-3">
                    <h3 className="font-medium text-sm mb-1">{opp.title}</h3>
                    <p className="text-xs text-muted-foreground mb-2">{opp.description}</p>
                    <Badge variant="outline" className="text-[10px]">{opp.supplier}</Badge>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          {/* Recommended Actions */}
          <Card className="bg-card/50 border-border/50">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-primary" /> Recommended Actions
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2.5">
                {brief.recommendedActions.map((action, i) => (
                  <div key={i} className="flex gap-3 text-sm">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs text-primary font-medium">
                      {i + 1}
                    </span>
                    <span className="text-muted-foreground">{action}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Monitoring */}
          <Card className="bg-card/50 border-border/50">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <Clock className="h-4 w-4" /> Monitoring Cadence
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{brief.monitoringFrequency}</p>
            </CardContent>
          </Card>

          {/* Footer */}
          <div className="text-center py-4 text-xs text-muted-foreground border-t border-border/30">
            Generated by Keiretsu Radar — Powered by Bright Data & AI
          </div>
        </div>
      </main>
    </div>
  );
}

export default function BriefPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full" /></div>}>
      <BriefContent />
    </Suspense>
  );
}
